### ISSUE TITLE
URI support

### ISSUE THREAD

**Issue by Quorafind** [reuseman/flashcards-obsidian#1]
**Is your feature request related to a problem? Please describe.**
URI: `obsidian://open?`
When I just wanted to read those card related notes or used anki to remind me of reviewing a whole note, I had to copy its original URI then paste it into a card.

**Describe the solution you'd like**
When plugin works to export notes' cards, combine them with URI from Obsidian. 

**Describe alternatives you've considered**
None.

**Additional context**
Like the URI support in obsidian.

**Comment by reuseman** [comment]
@Quorafind I've just released the new version where this feature is enabled

**Comment by yo-goto** [comment]
@reuseman Hi, thank you for making a great plugin. How can I include URI from my notes? Are there any buttons to configure including?

**Comment by reuseman** [comment]
> @reuseman Hi, thank you for making a great plugin. How can I include URI from my notes? Are there any buttons to configure including?

Whenever you insert an internal Obsidian link, for example [[my note]], it should automatically work in Anki.

**Comment by yo-goto** [comment]
thank you. I got it. 
If it is possible to include URI automatically, I think that also would be so convenient. Please consider adding the feature.

**Comment by yo-goto** [comment]
Wow. Your development is so fast! Thank you.
