### ISSUE TITLE
Probably last update ruin the plugin

### ISSUE THREAD

**Issue by glitchlover** [reuseman/flashcards-obsidian#10]
**NOTE: Do you have the last version of the plugin? If not that's probably the problem**

**Describe the bug**
I have write down my note as you tell
it doesnot recognize my deck name
Only producing the first #card deck
and ignoring other

**To Reproduce**
- Steps to reproduce the behavior:
1. Write down my notes
![image](https://user-images.githubusercontent.com/59877631/102683088-a623f000-41f8-11eb-9889-32f75b85e140.png)
![image](https://user-images.githubusercontent.com/59877631/102683092-a8864a00-41f8-11eb-954b-f120cadcd0fd.png)

2. Click on 'Flashcard insert' command pallate
3. went to anki
![image](https://user-images.githubusercontent.com/59877631/102683109-cb186300-41f8-11eb-8d63-67f335e3d1d3.png)
![image](https://user-images.githubusercontent.com/59877631/102683113-d2d80780-41f8-11eb-8a6b-44d0462e7f06.png)

**Expected behavior**
Expected three cards in anki

**Markdown used**
```md
---
ankified?: no
lecture:
subject:
tag:
date:  Saturday 19th, Dec 2020 (354th)
status: [ongoing]
cards-deck: Math::Geometry::Parabola
---

 # Equation of Parabola
 
 ## The Standard equation of parabola #card 
 - $y^2 = 4ax$
 - $(y-k)^2=4a(x-k)$
 - ![[Pasted image 20201219122607.png]]
 
 
 
### describing the image ![[Pasted image 20201219122703.png]] #card 
- In this vertex is (h,k);
- focus is (h+a,k);
- Equation of directrix: x = h-a
 
 
 
 ### all possible parabola #card
 ![parabola](https://d1whtlypfis84e.cloudfront.net/guides/wp-content/uploads/2018/05/12093024/Parabola-2.jpg)
^1608360431214



```

**Additional context**
It sometimes doesn't recognize my card deck name

**Comment by reuseman** [comment]
@glitchlover is possible that your empty lines actually contain some strange tab character?

**Comment by glitchlover** [comment]
maybe but the only thing I have done is add more space between two card. I will update my ans tomorrow

**Comment by glitchlover** [comment]
hmmm you are right! I have some space character. After removing them three cards really appeared! 
Thanks for the reply 😀. But you have to clear this things in readme so people could understand this plugin
