### ISSUE TITLE
#card NOT working

### ISSUE THREAD

**Issue by Palvehelmed** [reuseman/flashcards-obsidian#11]
**NOTE: Do you have the last version of the plugin? If not that's probably the problem**
Version: 1.0.5 (currently installed: 1.0.5)

**Describe the bug**
In my vault, `## This is the front #card  ` cannot gennerate a card but `My question::My answer` could, I have no idea how did this happen

**To Reproduce**
- Steps to reproduce the behavior:

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/36530040/102694618-372cb280-425d-11eb-943d-a05384bf96b2.png)

**Markdown used**
```md
# Question #card
Answer
```

**Additional context**

**Comment by reuseman** [comment]
Because you actually have a line of space between the heading and the content. When you put the #card tag, you're actually taking as answer the immediate line after
