### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by mycaule** [reuseman/flashcards-obsidian#111]
**Describe the bug**

Can't connect to Anki due to a CORS problem.

```
Access to XMLHttpRequest at 'http://127.0.0.1:8765/' from origin 'app://obsidian.md' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'http://localhost' that is not equal to the supplied origin.
```

**To Reproduce**
- Steps to reproduce the behavior:
1. Open Anki with Anki Connect
2. Go to 'Flashcards: Generate for the current file'

**Expected behavior**
Data should be sent to Anki application

**Screenshots**

<img width="261" alt="Screenshot 2022-05-31 at 08 58 21" src="https://user-images.githubusercontent.com/6161385/171111580-5ad98322-2adb-4099-9ca0-d7ad99d8443b.png">

**Markdown used**
```md
# Question #card
Answer
```

**Comment by reuseman** [comment]
@mycaul Did you do the **activate step **

       Settings> Flashcards > Give permission > Grant permission while Anki is open?

**Comment by mycaule** [comment]
thanks it works now
