### ISSUE TITLE
Can't create multiline cloze

### ISSUE THREAD

**Issue by hidara2000** [reuseman/flashcards-obsidian#119]
**Describe the bug**
It is not possible to create a multiline cloze. Each line seperated by a newline character is treated as a separate cloze

**Markdown used**
```md
---
tags: 
cards-deck: Modelling::Week 44 - Cloze
---

1.. it forces us to {1:think} about all of the parts of the model <br>2.. it helps us to {2:communicate} our model clearly to others<br>3.. it forms the basis for our model {3:implementation}


a.. it forces us to {1:think} about all of the parts of the model
b.. it helps us to {2:communicate} our model clearly to others
c.. it forms the basis for our model {3:implementation}

```

**To Reproduce**
- Steps to reproduce the behavior:
1. enter data as above results in the visual representation below in obsidian
![image](https://user-images.githubusercontent.com/15170494/183549682-0b26ded1-d64c-4cd9-b405-df7e989d6812.png)
2. sent to Anki
![image](https://user-images.githubusercontent.com/15170494/183549748-f3ba5332-1537-42f6-b682-78567483da95.png)

**Expected behavior**
in the first batch each line has no newline character but I entered a blank equation as a hack eg <br>
This simulates a newline and my flashcard appears as expected with all three lines
![image](https://user-images.githubusercontent.com/15170494/183549888-1a992428-0293-4fdc-83c7-7e9e63bf1b4c.png)
![image](https://user-images.githubusercontent.com/15170494/183550115-8f1bc1b2-b7c1-4893-9a21-6df4695fd8de.png)
![image](https://user-images.githubusercontent.com/15170494/183550147-e270deae-b359-48ee-b1ad-0c435ddc8082.png)

**Actual Behaviour**
in the second section the plugin puts each line in as a separate cloze flashcard
![image](https://user-images.githubusercontent.com/15170494/183550035-281f59dd-9b12-4102-b3d7-c702dd096e53.png)
![image](https://user-images.githubusercontent.com/15170494/183550323-5357c942-e0be-4d9b-8dc5-3e4596481b38.png)
![image](https://user-images.githubusercontent.com/15170494/183550361-656d707b-2808-4ced-97a7-6520a113257b.png)

**Screenshots**

**Additional context**
Would it be possible to change so if text is only separated by one newline that it is treated as a block (similar to first batch above) and if there is more than one newline character it behaves as second batch?

Cheers for all the work. This plugin has been invaluable :)

**Comment by putzwasser** [comment]
I'd say it's a design decision. Changing this would be a breaking change.

You can work around that by making use of `<br>` tags, as you did.

**Comment by hidara2000** [comment]
Fair enough and thank you
