### ISSUE TITLE
Cloze Hint

### ISSUE THREAD

**Issue by jaxxor44** [reuseman/flashcards-obsidian#121]
**Is your feature request related to a problem? Please describe.**
The ability to add hints for a cloze entry is always entering my mind.

**Describe the solution you'd like**
have a Cloze field `{1:foo}` 
Allow for hints to be inserted in some format like:
`{1:something:Hint}`

**Describe alternatives you've considered**
Currently the workaround is to manually add hints when I'm sure my cards wont change anymore.

**Comment by Yourself1011** [comment]
You can do this like so `{1:something::Hint}`
This will become `{{c1::something::hint}}` in Anki, which works fine

**Comment by jaxxor44** [comment]
Man, all I missed was another stupid : 
Thanks.
