### ISSUE TITLE
There is no configuration under "Paste the configuration below" in README.md

### ISSUE THREAD

**Issue by HeroJeanPierre** [reuseman/flashcards-obsidian#124]
Just what the title says.

**Comment by Ali-C-Ila** [comment]
Yeah, same problem here. Where exactly is that configuration ?

**Comment by Ali-C-Ila** [comment]
Copied this from another Anki-based plugin, appears to work.
https://github.com/Pseudonium/Obsidian_to_Anki/wiki/Images/AnkiConnect_ConfigREAL.png

But having to look into another plugin just to make yours work is absurd, fix this plz.

**Comment by reuseman** [comment]
Guys, that's a typo of the previous configuration process. Now is not needed anymore, and the plugin will automatically ask for permission. But you are indeed right, I didn't notice it, so I am going to remove it.
