### ISSUE TITLE
Error, could not add: xxx

### ISSUE THREAD

**Issue by Jackiexiao** [reuseman/flashcards-obsidian#13]
run `command : generate for current file `, raise Error: `Error, could not add: `shell里`;`和`&&`的区别`

file content:
```
shell里`;`和`&&`的区别 :: `;`前一个fail后面会继续执行，`&&`则不会
```

when I delete ";" and "&&", generate flashcard successfully

**Comment by reuseman** [comment]
@Jackiexiao I cannot actually reproduce the bug, on my version it actually works

**Comment by MurphyWan** [comment]
> run `command : generate for current file `, raise Error: `Error, could not add: `shell里`;`和`&&`的区别`
> 
> file content:
> 
> ```
> shell里`;`和`&&`的区别 :: `;`前一个fail后面会继续执行，`&&`则不会
> ```
> 
> when I delete ";" and "&&", generate flashcard successfully


I have the same problem here，raise Error: `Error, could not add xxx
but I don't know how to fix it ?
