### ISSUE TITLE
Plugin ceases to create flashcards. 

### ISSUE THREAD

**Issue by jaded0** [reuseman/flashcards-obsidian#143]
After the big obsidian update, I managed to create a few flashcards, but upon running the 'Generate for the current file' command, there is no error message and no response whatsoever. Anki does not show new flashcards made, nor do the little '^1666026165215' type tags show up in my note. 
I'm using Ubuntu Linux.
In settings, clicking, the 'test' button creates a message saying "Anki works."

**Comment by jaded0** [comment]
It works again if I close every single other tab.

**Comment by jaded0** [comment]
Ok, now I restarted my computer, opened obsidian and anki, created the simplest possible flashcard:
```
ok::a card
```
And, nothing. Nothing happens.

**Comment by jaded0** [comment]
Here's the log from anki:

[request]
{
    "action": "version",
    "params": {},
    "version": 6
}

[reply]
{
    "error": null,
    "result": 6
}

[request]
{
    "action": "version",
    "params": {},
    "version": 6
}

[reply]
{
    "error": null,
    "result": 6
}

[request]
{
    "action": "retrieveMediaFile",
    "params": {
        "filename": "_highlightInit.js"
    },
    "version": 6
}

[reply]
{
    "error": null,
    "result": "ZG9jdW1lbnQucXVlcnlTZWxlY3RvckFsbCgncHJlIGNvZGUnKS5mb3JFYWNoKChibG9jaykgPT4gewogICAgaGxqcy5oaWdobGlnaHRCbG9jayhibG9jayk7Cn0pOw=="
}

[request]
{
    "action": "multi",
    "params": {
        "actions": [
            {
                "action": "createModel",
                "params": {
                    "cardTemplates": [
                        {
                            "Back": "{{FrontSide}}\n\n<hr id=answer>\n\n{{Back}}\r\n<br><br>\r\n<small>Source: {{Source}}</small>",
                            "Front": "{{Front}}\r\n<p class=\"tags\">{{Tags}}</p>\r\n\r\n<script>\r\n    var tagEl = document.querySelector('.tags');\r\n    var tags = tagEl.innerHTML.split(' ');\r\n    var html = '';\r\n    tags.forEach(function(tag) {\r\n\tif (tag) {\r\n\t    var newTag = '<span class=\"tag\">' + tag + '</span>';\r\n           html += newTag;\r\n    \t    tagEl.innerHTML = html;\r\n\t}\r\n    });\r\n    \r\n</script>",
                            "Name": "Front / Back"
                        }
                    ],
                    "css": ".card {\r\n font-family: arial;\r\n font-size: 20px;\r\n text-align: center;\r\n color: black;\r\n background-color: white;\r\n}\r\n\r\n.tag::before {\r\n\tcontent: \"#\";\r\n}\r\n\r\n.tag {\r\n  color: white;\r\n  background-color: #9F2BFF;\r\n  border: none;\r\n  font-size: 11px;\r\n  font-weight: bold;\r\n  padding: 1px 8px;\r\n  margin: 0px 3px;\r\n  text-align: center;\r\n  text-decoration: none;\r\n  cursor: pointer;\r\n  border-radius: 14px;\r\n  display: inline;\r\n  vertical-align: middle;\r\n}\r\n .cloze { font-weight: bold; color: blue;}.nightMode .cloze { color: lightblue;}",
                    "inOrderFields": [
                        "Front",
                        "Back",
                        "Source"
                    ],
                    "modelName": "Obsidian-basic-source"
                }
            },
            {
                "action": "createModel",
                "params": {
                    "cardTemplates": [
                        {
                            "Back": "{{FrontSide}}\n\n<hr id=answer>\n\n{{Back}}\r\n<br><br>\r\n<small>Source: {{Source}}</small>",
                            "Front": "{{Front}}\r\n<p class=\"tags\">{{Tags}}</p>\r\n\r\n<script>\r\n    var tagEl = document.querySelector('.tags');\r\n    var tags = tagEl.innerHTML.split(' ');\r\n    var html = '';\r\n    tags.forEach(function(tag) {\r\n\tif (tag) {\r\n\t    var newTag = '<span class=\"tag\">' + tag + '</span>';\r\n           html += newTag;\r\n    \t    tagEl.innerHTML = html;\r\n\t}\r\n    });\r\n    \r\n</script>",
                            "Name": "Front / Back"
                        },
                        {
                            "Back": "{{FrontSide}}\n\n<hr id=answer>\n\n{{Front}}\r\n<br><br>\r\n<small>Source: {{Source}}</small>",
                            "Front": "{{Back}}\r\n<p class=\"tags\">{{Tags}}</p>\r\n\r\n<script>\r\n    var tagEl = document.querySelector('.tags');\r\n    var tags = tagEl.innerHTML.split(' ');\r\n    var html = '';\r\n    tags.forEach(function(tag) {\r\n\tif (tag) {\r\n\t    var newTag = '<span class=\"tag\">' + tag + '</span>';\r\n           html += newTag;\r\n    \t    tagEl.innerHTML = html;\r\n\t}\r\n    });\r\n    \r\n</script>",
                            "Name": "Back / Front"
                        }
                    ],
                    "css": ".card {\r\n font-family: arial;\r\n font-size: 20px;\r\n text-align: center;\r\n color: black;\r\n background-color: white;\r\n}\r\n\r\n.tag::before {\r\n\tcontent: \"#\";\r\n}\r\n\r\n.tag {\r\n  color: white;\r\n  background-color: #9F2BFF;\r\n  border: none;\r\n  font-size: 11px;\r\n  font-weight: bold;\r\n  padding: 1px 8px;\r\n  margin: 0px 3px;\r\n  text-align: center;\r\n  text-decoration: none;\r\n  cursor: pointer;\r\n  border-radius: 14px;\r\n  display: inline;\r\n  vertical-align: middle;\r\n}\r\n .cloze { font-weight: bold; color: blue;}.nightMode .cloze { color: lightblue;}",
                    "inOrderFields": [
                        "Front",
                        "Back",
                        "Source"
                    ],
                    "modelName": "Obsidian-basic-reversed-source"
                }
            },
            {
                "action": "createModel",
                "params": {
                    "cardTemplates": [
                        {
                            "Back": "{{cloze:Text}}\n\n<br>{{Extra}}\r\n<br><br>\r\n<small>Source: {{Source}}</small><script>\r\n    var tagEl = document.querySelector('.tags');\r\n    var tags = tagEl.innerHTML.split(' ');\r\n    var html = '';\r\n    tags.forEach(function(tag) {\r\n\tif (tag) {\r\n\t    var newTag = '<span class=\"tag\">' + tag + '</span>';\r\n           html += newTag;\r\n    \t    tagEl.innerHTML = html;\r\n\t}\r\n    });\r\n    \r\n</script>",
                            "Front": "{{cloze:Text}}\n\n<script>\r\n    var tagEl = document.querySelector('.tags');\r\n    var tags = tagEl.innerHTML.split(' ');\r\n    var html = '';\r\n    tags.forEach(function(tag) {\r\n\tif (tag) {\r\n\t    var newTag = '<span class=\"tag\">' + tag + '</span>';\r\n           html += newTag;\r\n    \t    tagEl.innerHTML = html;\r\n\t}\r\n    });\r\n    \r\n</script>",
                            "Name": "Cloze"
                        }
                    ],
                    "css": ".card {\r\n font-family: arial;\r\n font-size: 20px;\r\n text-align: center;\r\n color: black;\r\n background-color: white;\r\n}\r\n\r\n.tag::before {\r\n\tcontent: \"#\";\r\n}\r\n\r\n.tag {\r\n  color: white;\r\n  background-color: #9F2BFF;\r\n  border: none;\r\n  font-size: 11px;\r\n  font-weight: bold;\r\n  padding: 1px 8px;\r\n  margin: 0px 3px;\r\n  text-align: center;\r\n  text-decoration: none;\r\n  cursor: pointer;\r\n  border-radius: 14px;\r\n  display: inline;\r\n  vertical-align: middle;\r\n}\r\n .cloze { font-weight: bold; color: blue;}.nightMode .cloze { color: lightblue;}",
                    "inOrderFields": [
                        "Text",
                        "Extra",
                        "Source"
                    ],
                    "isCloze": true,
                    "modelName": "Obsidian-cloze-source"
                }
            },
            {
                "action": "createModel",
                "params": {
                    "cardTemplates": [
                        {
                            "Back": "{{FrontSide}}\n\n<hr id=answer>\ud83e\udde0 Review done.\r\n<br><br>\r\n<small>Source: {{Source}}</small>",
                            "Front": "{{Prompt}}\r\n<p class=\"tags\">\ud83e\udde0spaced {{Tags}}</p>\r\n\r\n<script>\r\n    var tagEl = document.querySelector('.tags');\r\n    var tags = tagEl.innerHTML.split(' ');\r\n    var html = '';\r\n    tags.forEach(function(tag) {\r\n\tif (tag) {\r\n\t    var newTag = '<span class=\"tag\">' + tag + '</span>';\r\n           html += newTag;\r\n    \t    tagEl.innerHTML = html;\r\n\t}\r\n    });\r\n    \r\n</script>",
                            "Name": "Spaced"
                        }
                    ],
                    "css": ".card {\r\n font-family: arial;\r\n font-size: 20px;\r\n text-align: center;\r\n color: black;\r\n background-color: white;\r\n}\r\n\r\n.tag::before {\r\n\tcontent: \"#\";\r\n}\r\n\r\n.tag {\r\n  color: white;\r\n  background-color: #9F2BFF;\r\n  border: none;\r\n  font-size: 11px;\r\n  font-weight: bold;\r\n  padding: 1px 8px;\r\n  margin: 0px 3px;\r\n  text-align: center;\r\n  text-decoration: none;\r\n  cursor: pointer;\r\n  border-radius: 14px;\r\n  display: inline;\r\n  vertical-align: middle;\r\n}\r\n .cloze { font-weight: bold; color: blue;}.nightMode .cloze { color: lightblue;}",
                    "inOrderFields": [
                        "Prompt",
                        "Source"
                    ],
                    "modelName": "Obsidian-spaced-source"
                }
            }
        ]
    },
    "version": 6
}

[request]
{
    "action": "createModel",
    "params": {
        "cardTemplates": [
            {
                "Back": "{{FrontSide}}\n\n<hr id=answer>\n\n{{Back}}\r\n<br><br>\r\n<small>Source: {{Source}}</small>",
                "Front": "{{Front}}\r\n<p class=\"tags\">{{Tags}}</p>\r\n\r\n<script>\r\n    var tagEl = document.querySelector('.tags');\r\n    var tags = tagEl.innerHTML.split(' ');\r\n    var html = '';\r\n    tags.forEach(function(tag) {\r\n\tif (tag) {\r\n\t    var newTag = '<span class=\"tag\">' + tag + '</span>';\r\n           html += newTag;\r\n    \t    tagEl.innerHTML = html;\r\n\t}\r\n    });\r\n    \r\n</script>",
                "Name": "Front / Back"
            }
        ],
        "css": ".card {\r\n font-family: arial;\r\n font-size: 20px;\r\n text-align: center;\r\n color: black;\r\n background-color: white;\r\n}\r\n\r\n.tag::before {\r\n\tcontent: \"#\";\r\n}\r\n\r\n.tag {\r\n  color: white;\r\n  background-color: #9F2BFF;\r\n  border: none;\r\n  font-size: 11px;\r\n  font-weight: bold;\r\n  padding: 1px 8px;\r\n  margin: 0px 3px;\r\n  text-align: center;\r\n  text-decoration: none;\r\n  cursor: pointer;\r\n  border-radius: 14px;\r\n  display: inline;\r\n  vertical-align: middle;\r\n}\r\n .cloze { font-weight: bold; color: blue;}.nightMode .cloze { color: lightblue;}",
        "inOrderFields": [
            "Front",
            "Back",
            "Source"
        ],
        "modelName": "Obsidian-basic-source"
    }
}

[reply]
{
    "error": "Model name already exists",
    "result": null
}

[request]
{
    "action": "createModel",
    "params": {
        "cardTemplates": [
            {
                "Back": "{{FrontSide}}\n\n<hr id=answer>\n\n{{Back}}\r\n<br><br>\r\n<small>Source: {{Source}}</small>",
                "Front": "{{Front}}\r\n<p class=\"tags\">{{Tags}}</p>\r\n\r\n<script>\r\n    var tagEl = document.querySelector('.tags');\r\n    var tags = tagEl.innerHTML.split(' ');\r\n    var html = '';\r\n    tags.forEach(function(tag) {\r\n\tif (tag) {\r\n\t    var newTag = '<span class=\"tag\">' + tag + '</span>';\r\n           html += newTag;\r\n    \t    tagEl.innerHTML = html;\r\n\t}\r\n    });\r\n    \r\n</script>",
                "Name": "Front / Back"
            },
            {
                "Back": "{{FrontSide}}\n\n<hr id=answer>\n\n{{Front}}\r\n<br><br>\r\n<small>Source: {{Source}}</small>",
                "Front": "{{Back}}\r\n<p class=\"tags\">{{Tags}}</p>\r\n\r\n<script>\r\n    var tagEl = document.querySelector('.tags');\r\n    var tags = tagEl.innerHTML.split(' ');\r\n    var html = '';\r\n    tags.forEach(function(tag) {\r\n\tif (tag) {\r\n\t    var newTag = '<span class=\"tag\">' + tag + '</span>';\r\n           html += newTag;\r\n    \t    tagEl.innerHTML = html;\r\n\t}\r\n    });\r\n    \r\n</script>",
                "Name": "Back / Front"
            }
        ],
        "css": ".card {\r\n font-family: arial;\r\n font-size: 20px;\r\n text-align: center;\r\n color: black;\r\n background-color: white;\r\n}\r\n\r\n.tag::before {\r\n\tcontent: \"#\";\r\n}\r\n\r\n.tag {\r\n  color: white;\r\n  background-color: #9F2BFF;\r\n  border: none;\r\n  font-size: 11px;\r\n  font-weight: bold;\r\n  padding: 1px 8px;\r\n  margin: 0px 3px;\r\n  text-align: center;\r\n  text-decoration: none;\r\n  cursor: pointer;\r\n  border-radius: 14px;\r\n  display: inline;\r\n  vertical-align: middle;\r\n}\r\n .cloze { font-weight: bold; color: blue;}.nightMode .cloze { color: lightblue;}",
        "inOrderFields": [
            "Front",
            "Back",
            "Source"
        ],
        "modelName": "Obsidian-basic-reversed-source"
    }
}

[reply]
{
    "error": "Model name already exists",
    "result": null
}

[request]
{
    "action": "createModel",
    "params": {
        "cardTemplates": [
            {
                "Back": "{{cloze:Text}}\n\n<br>{{Extra}}\r\n<br><br>\r\n<small>Source: {{Source}}</small><script>\r\n    var tagEl = document.querySelector('.tags');\r\n    var tags = tagEl.innerHTML.split(' ');\r\n    var html = '';\r\n    tags.forEach(function(tag) {\r\n\tif (tag) {\r\n\t    var newTag = '<span class=\"tag\">' + tag + '</span>';\r\n           html += newTag;\r\n    \t    tagEl.innerHTML = html;\r\n\t}\r\n    });\r\n    \r\n</script>",
                "Front": "{{cloze:Text}}\n\n<script>\r\n    var tagEl = document.querySelector('.tags');\r\n    var tags = tagEl.innerHTML.split(' ');\r\n    var html = '';\r\n    tags.forEach(function(tag) {\r\n\tif (tag) {\r\n\t    var newTag = '<span class=\"tag\">' + tag + '</span>';\r\n           html += newTag;\r\n    \t    tagEl.innerHTML = html;\r\n\t}\r\n    });\r\n    \r\n</script>",
                "Name": "Cloze"
            }
        ],
        "css": ".card {\r\n font-family: arial;\r\n font-size: 20px;\r\n text-align: center;\r\n color: black;\r\n background-color: white;\r\n}\r\n\r\n.tag::before {\r\n\tcontent: \"#\";\r\n}\r\n\r\n.tag {\r\n  color: white;\r\n  background-color: #9F2BFF;\r\n  border: none;\r\n  font-size: 11px;\r\n  font-weight: bold;\r\n  padding: 1px 8px;\r\n  margin: 0px 3px;\r\n  text-align: center;\r\n  text-decoration: none;\r\n  cursor: pointer;\r\n  border-radius: 14px;\r\n  display: inline;\r\n  vertical-align: middle;\r\n}\r\n .cloze { font-weight: bold; color: blue;}.nightMode .cloze { color: lightblue;}",
        "inOrderFields": [
            "Text",
            "Extra",
            "Source"
        ],
        "isCloze": true,
        "modelName": "Obsidian-cloze-source"
    }
}

[reply]
{
    "error": "Model name already exists",
    "result": null
}

[request]
{
    "action": "createModel",
    "params": {
        "cardTemplates": [
            {
                "Back": "{{FrontSide}}\n\n<hr id=answer>\ud83e\udde0 Review done.\r\n<br><br>\r\n<small>Source: {{Source}}</small>",
                "Front": "{{Prompt}}\r\n<p class=\"tags\">\ud83e\udde0spaced {{Tags}}</p>\r\n\r\n<script>\r\n    var tagEl = document.querySelector('.tags');\r\n    var tags = tagEl.innerHTML.split(' ');\r\n    var html = '';\r\n    tags.forEach(function(tag) {\r\n\tif (tag) {\r\n\t    var newTag = '<span class=\"tag\">' + tag + '</span>';\r\n           html += newTag;\r\n    \t    tagEl.innerHTML = html;\r\n\t}\r\n    });\r\n    \r\n</script>",
                "Name": "Spaced"
            }
        ],
        "css": ".card {\r\n font-family: arial;\r\n font-size: 20px;\r\n text-align: center;\r\n color: black;\r\n background-color: white;\r\n}\r\n\r\n.tag::before {\r\n\tcontent: \"#\";\r\n}\r\n\r\n.tag {\r\n  color: white;\r\n  background-color: #9F2BFF;\r\n  border: none;\r\n  font-size: 11px;\r\n  font-weight: bold;\r\n  padding: 1px 8px;\r\n  margin: 0px 3px;\r\n  text-align: center;\r\n  text-decoration: none;\r\n  cursor: pointer;\r\n  border-radius: 14px;\r\n  display: inline;\r\n  vertical-align: middle;\r\n}\r\n .cloze { font-weight: bold; color: blue;}.nightMode .cloze { color: lightblue;}",
        "inOrderFields": [
            "Prompt",
            "Source"
        ],
        "modelName": "Obsidian-spaced-source"
    }
}

[reply]
{
    "error": "Model name already exists",
    "result": null
}

[reply]
{
    "error": null,
    "result": [
        {
            "error": "Model name already exists",
            "result": null
        },
        {
            "error": "Model name already exists",
            "result": null
        },
        {
            "error": "Model name already exists",
            "result": null
        },
        {
            "error": "Model name already exists",
            "result": null
        }
    ]
}

[request]
{
    "action": "createDeck",
    "params": {
        "deck": "default_obsidian"
    },
    "version": 6
}

[reply]
{
    "error": null,
    "result": 1651360049944
}

[request]
{
    "action": "notesInfo",
    "params": {
        "notes": []
    },
    "version": 6
}

[reply]
{
    "error": null,
    "result": []
}

[request]
{
    "action": "version",
    "params": {},
    "version": 6
}

[reply]
{
    "error": null,
    "result": 6
}

**Comment by jaded0** [comment]
Update: The issue does not occur if I remove the embedded image that I had placed a few lines below my inline flashcard.

**Comment by reuseman** [comment]
Probably there is something wrong with the new update of Obsidian

**Comment by xverbatim1971** [comment]
I also have the same problem.
Windows 10
Flashcards are not created.
Connection to Anki is established, but nothing happens after pressing the "generate" button. 
after a restart of obsidian it worked.

is it important in which mode you have the note open?
difference between preview or editmode?
I am not sure

thanks for the plugin 
and the effort in the work

i hope the bug will be found

**Comment by szbbas** [comment]
Similar problems for me as well on macOS Catalina. I do not even see Connection to Anki is established, and even the small symbol of the plugin on the left/right pane disappeared.
I love this plugin, before the big Obsidian update it used to be a crucial pillar for my learning process. Many thanks for the creation, I hope the bug can be fixed.

**Comment by szbbas** [comment]
Similar problems for me as well on macOS Catalina, the cards are not created anymore.
I love this plugin, before the big Obsidian update it used to be a crucial pillar for my learning process. Many thanks for the creation, I hope the bug can be fixed!

**Comment by Schabolon** [comment]
I encountered a similar problem.
For me the card generation worked again after removing an embedded image from the .md file. (the image was NOT in the flashcards).
Hope this helps.

**Comment by JH-Stuvansys** [comment]
I think I know where in your code it's breaking. Here:
![image](https://user-images.githubusercontent.com/71874372/196776188-ddcd4130-6811-474e-9d4c-2738aa3871ff.png)

The reason:
![image](https://user-images.githubusercontent.com/71874372/196776220-870c4d20-7aa9-4a68-8dfd-b94033df2e0f.png)

I would love to help with bugfixing, but I'm a freelancer (with 2 companies, among others as a software engineer for major customers like Daimler) and on the side I'm doing my master and have a daughter. Just wanted to help you a bit, because I read somewhere that you are looking for support and I use your plugin super gladly and as a colleague knows exactly how it is when the bugs paralyze you. 

BTW: Strange I find the occupation of my port with this strange service. The ensures that at the beginning of this error is thrown:

![image](https://user-images.githubusercontent.com/71874372/196777039-b56e2766-5387-411c-ae37-0c08b5bee5c6.png)

**Comment by JH-Stuvansys** [comment]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/71874372/196887283-114af04c-3fa3-41df-8d3f-9dddd42c5593.png">

This happens, when i take a fresh markdown-file. I dont know wether card.ts line 100 is refererring to the minified version of the typescript file. But far away from that and please dont take it personal, but i would avoid putting too much code in a try catch block. I do programming since about 30 years and i did many code reviews and i was never strict in a sense of doing formalism that helps nobody. But thats really a point that makes it hard to find bugs. I will now switch for the meanwhile to neuracacne, because i have stress for learning for my master (in artificial intelligence, many hardcore-math stuff i didnt have in my cs bachelor) so i need asap a new solution. When you have fixed the bug, you will surely release a new version. I will come back then. Like i have said, i am a big fan of your tool.

**Comment by erfanbashar1q** [comment]
I also have the same problem with creating cards if i have embeded image, when i remove the "!" from the first of embeded image, it can be generated.
in a file presence of just one "!" is equal to this bug


thank you for your support

**Comment by ivyraine** [comment]
I was able to reproduce the bug by adding an embedded image (ex `![[image.png]]`) to any flashcard style.

**Comment by ivyraine** [comment]
It appears that this line in `parser.ts`
```ts
      var embedContentHtml = el.getElementsByClassName('markdown-embed-content')[0];
```
now fails to retrieve any html elements. 

Looking into fixes now

**Comment by ivyraine** [comment]
I have a working solution in `https://github.com/ivyraine/flashcards-obsidian/tree/143`

However, before merging it should be backwards compatible:
@jaded0 @Schabolon @JH-Stuvansys @xverbatim1971 Did this error occur in previous Obsidian versions? What was the last working version?

**Comment by xverbatim1971** [comment]
the problem was from version 1.0 - the current version.
there were also image problems. before that, everything worked fine. the images were displayed to me and the cards produced.

now i don't do anything with images and so far everything is ok...
I have only noticed that the information is sometimes not correct. information such as update, created - but directly in anki I have not noticed anything.



Translated with www.DeepL.com/Translator (free version)

**Comment by JH-Stuvansys** [comment]
> It appears that this line in `parser.ts`
> 
> ```ts
>       var embedContentHtml = el.getElementsByClassName('markdown-embed-content')[0];
> ```
> 
> now fails to retrieve any html elements.
> 
> Looking into fixes now

Well done. I just have hab a quick look and if you follow down the stacktrace, you see that the core work is done by the parser.

**Comment by JH-Stuvansys** [comment]
> the problem was from version 1.0 - the current version. there were also image problems. before that, everything worked fine. the images were displayed to me and the cards produced.
> 
> now i don't do anything with images and so far everything is ok... I have only noticed that the information is sometimes not correct. information such as update, created - but directly in anki I have not noticed anything.
> 

Like xverbatim1971 said: The error appears the first time after the "Big Update / Upgrade" of Obsidian.

**Comment by reuseman** [comment]
@ivyraine I've just done a quick test on my machine, and it doesn't seem fixed

**Comment by reuseman** [comment]
Now it should work, the problem seemed to be the fact that after the pull request #114, the embedded images were treated as an embedded block
