### ISSUE TITLE
Changing Deck Title not acting as expected

### ISSUE THREAD

**Issue by gdxn96** [reuseman/flashcards-obsidian#15]
**NOTE: Do you have the last version of the plugin? If not that's probably the problem**
I have `1.0.7`

**Describe the bug**
When changing the deck from default to something custom, the notes that were previously created don't get moved from default to the new deck.

**To Reproduce**
1. Make a card in a new notes file
2. Sync to anki
3. Change `cards-deck: default` to `cards-deck: Something Custom`
4. Hit Sync again
5. Cards previously created in `default` deck are stuck in `default` deck

**Expected behavior**
1. Existing cards are duplicated to new deck
2. Existing cards are removed from default deck

**Comment by reuseman** [comment]
I've implemented this feature. Now it should work, let me know

**Comment by gdxn96** [comment]
@reuseman obsidian can't detect the new version, do you also need to update the version number in `manifest.json` maybe?

**Comment by gdxn96** [comment]
I modified the manifest manually and it's working as expected 👌 🚀

**Comment by reuseman** [comment]
> @reuseman obsidian can't detect the new version, do you also need to update the version number in `manifest.json` maybe?

Yeah the problem was the manifest, I did not update in a while and I forgot a little the whole procedure 😁
