### ISSUE TITLE
Deck name based on the folder name

### ISSUE THREAD

**Issue by jakeoung** [reuseman/flashcards-obsidian#17]
**Describe the solution you'd like**
If I have a md file: /math/complex/theorem.md, then, I wish that the plugin could automatically generate the decker name as `math::complex`. So in the setting, we could choose the fixed deck name or automatic name based on the parent folder. 

If it supports, I would very appreciate!

**Comment by elias-blm** [comment]
It would be very very *great*!

**Comment by reuseman** [comment]
I am actually not using it in that way, but I can see the value of it. So whenever I have a bit of time I am going to implement it as an option to be enabled in the settings. In the meanwhile, pull request are more than welcomed if you want

**Comment by Rainvoo** [comment]
This feather is great!

**Comment by TobiasKlosek** [comment]
+1 on that!

**Comment by Hxppdv** [comment]
This feature is important, in fact it's the reason I'm still using [obsidian to anki](https://github.com/niposch/Obsidian_to_Anki)

**Comment by reuseman** [comment]
This is now up @jakeoung @elias-blm @Rainvoo @TobiasKlosek @Hxppdv. Sorry if it took a while.

**Comment by jakeoung** [comment]
Thanks for updating it, but it seems not working. A pull request seems to fix an issue.
