### ISSUE TITLE
Flashcards fail to sync to Anki

### ISSUE THREAD

**Issue by hf02** [reuseman/flashcards-obsidian#176]
**Describe the bug**
Flashcards fail to sync to Anki.

**To Reproduce**
1. Sync.
2. Works the first time.
3. After the second, it seems to do nothing.

**Expected behavior**
It should sync to Anki.

**Markdown used**
```md
---
cards-deck: test
---

h::hello
^1675266864355
```

**Additional context**
I've restarted both Obsidian and Anki. It outputs this error in the console upon syncing:

![image](https://user-images.githubusercontent.com/55464333/216096683-6da2309e-1459-47a9-ae6f-2719e91858a1.png)

**Comment by hf02** [comment]
i found the issue. i removed all of the ids in this one note i have (i guess it still effected my minimal reproduction note somehow), had it regenerate, and now it's working. i guess i have an invalid id somewhere, but i have no idea which one. made #177.

**Comment by harmtemolder** [comment]
I have the same issue, and it took me a while to find this issue because I was searching for the text of the error message, but that's in a screenshot here. So I'll add it as text as well:

```
__init__() missing 3 required positional arguments: 'help_page', 'context', and 'backtrace'
```
