### ISSUE TITLE
The tag hierarchy does not work when exporting to Anki.

### ISSUE THREAD

**Issue by cjdduarte** [reuseman/flashcards-obsidian#20]
The tag hierarchy does not work when exporting to Anki.
It creates a card in the tag structure.

![image](https://user-images.githubusercontent.com/42243532/105753479-871b2b00-5f27-11eb-96cd-61763b61f6b3.png)

**Comment by reuseman** [comment]
Hey this should be solved right now, let me know

**Comment by cjdduarte** [comment]
It worked

**Comment by cjdduarte** [comment]
Sorry, but it didn't work.
Just seen it now.

Look

****
![image](https://user-images.githubusercontent.com/42243532/106732914-07a8ee00-65f0-11eb-9c37-dc7c543ab98f.png)

the terms were separated into two separate tags.
![image](https://user-images.githubusercontent.com/42243532/106732972-17283700-65f0-11eb-8562-c1fefa3c87f8.png)

The correct should be like this:
![image](https://user-images.githubusercontent.com/42243532/106733165-4d65b680-65f0-11eb-8a32-1dd710676f84.png)

**Comment by reuseman** [comment]
Now it should work properly

**Comment by cjdduarte** [comment]
It worked
