### ISSUE TITLE
This Hyperlink formatting does not work.

### ISSUE THREAD

**Issue by cjdduarte** [reuseman/flashcards-obsidian#23]
This Hyperlink formatting does not work:

![image](https://user-images.githubusercontent.com/42243532/106755104-7dbb4e00-660c-11eb-96c3-2cf6f669c4af.png)

![image](https://user-images.githubusercontent.com/42243532/106755163-8c096a00-660c-11eb-894e-bdf3ecf30719.png)

![image](https://user-images.githubusercontent.com/42243532/106755190-962b6880-660c-11eb-8811-8d71837c0aa6.png)

![image](https://user-images.githubusercontent.com/42243532/106755219-9fb4d080-660c-11eb-8d71-fe1355097161.png)

**Comment by reuseman** [comment]
It should work now, let me know

**Comment by cjdduarte** [comment]
Its OK. Tanks!!!!!!
