### ISSUE TITLE
Image resize syntax prevents image from getting exported

### ISSUE THREAD

**Issue by TJay21** [reuseman/flashcards-obsidian#24]
**Describe the bug**
When using the resize syntax e.g. ![[image|200x200]] the image isn't attached to the flashcard.

**To Reproduce**
See screenshots

**Expected behavior**
Export image in resized ratio or at least in original ratio.

**Screenshots**
![01](https://user-images.githubusercontent.com/78580547/106991304-3cdf4880-6776-11eb-918c-7c2cceea42ec.jpg)
![02](https://user-images.githubusercontent.com/78580547/106991312-41a3fc80-6776-11eb-856f-b137e3d971ec.jpg)

**Comment by reuseman** [comment]
This now should be fixed, let me know

**Comment by TJay21** [comment]
Works fine
Well done!
