### ISSUE TITLE
Updating / Deleting #cards and perhaps UTF-8 issues

### ISSUE THREAD

**Issue by mkschulze** [reuseman/flashcards-obsidian#28]
![Bildschirmfoto 2021-02-20 um 16 36 00](https://user-images.githubusercontent.com/3390820/108601913-77b0c580-739f-11eb-97e9-aa87b93d92e4.png)

**Describe the bug**
When I delete a card after initial generation, I get a lot of Error, could not add `xxx`

I suspect this to be an error with UTF-8 support maybe, as I've seen that the tag creation gets confused. See also #13 Error, could not add: xxx, which could be related.

**To Reproduce**
- Steps to reproduce the behavior:
1. Paste the following
```
---
tags: Umsatzsteuer, Lösungsschema
cards-deck: Umsatzsteuer::Lösungsschema
---
# Lösungsschema USt 
#card
## 1. Allgemeines
#card
### 1.1 Klausuraufbau 
#card

1. Vorspann
	1. Unternehmereigenschaft
	2. Rahmen des Unternehmens
	3. Besteuerungsform (Regelbesteuerung oder Kleinunternehmer)
	4. Besteuerungsart (Soll- oder Ist-besteuerung)
	5. maßgeblicher Voranmeldezeitraum

### 1.2 Lösungsstil 
#card

Lösung im Urteilsstil
1. Ergebnis
2. §§-Angabe
3. Begründung (kann bei klaren Dingen weggeslassen werden)

```

2. After generation it looks like this:
```
---
tags: Umsatzsteuer, Lösungsschema
cards-deck: Umsatzsteuer::Lösungsschema
---

# Lösungsschema USt 
#card

## 1. Allgemeines
#card
^1613835543215

### 1.1 Klausuraufbau 
#card

1. Vorspann
	1. Unternehmereigenschaft
	2. Rahmen des Unternehmens
	3. Besteuerungsform (Regelbesteuerung oder Kleinunternehmer)
	4. Besteuerungsart (Soll- oder Ist-besteuerung)
	5. maßgeblicher Voranmeldezeitraum

^1613835543217

### 1.2 Lösungsstil 
#card

Lösung im Urteilsstil
1. Ergebnis
2. §§-Angabe
3. Begründung (kann bei klaren Dingen weggeslassen werden)
^1613835543219

```

3. now remove the card-reference after the second heading **_1.Allgemeines_** 

```
---
tags: Umsatzsteuer, Lösungsschema
cards-deck: Umsatzsteuer::Lösungsschema
---

# Lösungsschema USt 
#card

## 1. Allgemeines
#card

### 1.1 Klausuraufbau 
#card

1. Vorspann
	1. Unternehmereigenschaft
	2. Rahmen des Unternehmens
	3. Besteuerungsform (Regelbesteuerung oder Kleinunternehmer)
	4. Besteuerungsart (Soll- oder Ist-besteuerung)
	5. maßgeblicher Voranmeldezeitraum

^1613835543217

### 1.2 Lösungsstil 
#card

Lösung im Urteilsstil
1. Ergebnis
2. §§-Angabe
3. Begründung (kann bei klaren Dingen weggeslassen werden)
^1613835543219

```
this messes with tag creation and produces errors like: (note, I removed entries for this post to be more compact.)
![Bildschirmfoto 2021-02-20 um 16 32 17](https://user-images.githubusercontent.com/3390820/108601928-839c8780-739f-11eb-9e70-bda9545431a4.png)

Tags in Anki look like this then:

![Bildschirmfoto 2021-02-20 um 16 43 59](https://user-images.githubusercontent.com/3390820/108601940-9d3dcf00-739f-11eb-99c2-188534415785.png)

**Expected behavior**
Being able to delete and edit tags and cards without messing up card generation, probably related when using special characters that require UTF-8 encoding.

Without using special characters in the tags it looks like:
 
![Bildschirmfoto 2021-02-20 um 17 21 23](https://user-images.githubusercontent.com/3390820/108602072-4e446980-73a0-11eb-936e-96bd08236157.png)

**Additional context**
I'm not actually sure where this errors come from, but I try to investigate further.

**Comment by reuseman** [comment]
@mkschulze In the initial content that you pasted, it's not really clear to me why you use empty cards? Is that part of your workflow? You don't need those

```md
# Lösungsschema USt 
#card        <- why this?
## 1. Allgemeines
#card        <- why this?
### 1.1 Klausuraufbau 
#card

1. Vorspann
	1. Unternehmereigenschaft
	2. Rahmen des Unternehmens
	3. Besteuerungsform (Regelbesteuerung oder Kleinunternehmer)
	4. Besteuerungsart (Soll- oder Ist-besteuerung)
	5. maßgeblicher Voranmeldezeitraum
```

Second thing, the way you are deleting it's not the correct way. You need to delete the question and the answer, but not the card ID. Because otherwise, the cards are not deleted in Anki and thus the plugin will try to insert them again.
```md
## 1. Allgemeines         
#card
^1613835543215
```
So, this should be your final content and then you press "Generate flashcards"
```md
^1613835543215
```
Regarding the problem with tags, you are probably right, it may be something with UTF-8. I am going to check in the following days

**Comment by mkschulze** [comment]
I see ok, yea I thought I need to place #card below the headings to get the breadcrumb style heading into my card.

Ok, then it's probably just my misunderstanding how it should be done. Thanks for clarifying.

**Comment by reuseman** [comment]
It took me a while to find the time, but now the problem with non latin characters should be solved slightly_smiling_face
