### ISSUE TITLE
Tags use chinese words in markdown, can't create tag in Anki

### ISSUE THREAD

**Issue by blackcatIan** [reuseman/flashcards-obsidian#31]
**NOTE: Do you have the last version of the plugin? If not that's probably the problem**

**Describe the bug**
Situation：
I want to create tags write in chinese words, but failed
plugin version:1.1.9

**To Reproduce**
- Steps to reproduce the behavior:
1. create markdown file
2. write tags like  
`tags: 数学, C系列`
3. make a simple card
4. Generate flash card

**Expected behavior**
Automatically create chinese words tag in Anki.

**Reality result**
If the word startwith chinese word, Anki will not create tag
If the word startwith english word, Anki will only create the english part and ingore chinese part

**Screenshots**
None

**Markdown used**
```md
---
tags: 数学, C系列
cards-deck: 数学术语
---

# 什么是量纲？#card
- 量纲（dimension）是指物理量的基本属性。
```

**Additional context**
The bug problem maybe the regex in cards.ts at line 320
`globalTags = tags ? tags[1].match(/\[\[(.*?)\]\]|#([\w:\/-]+)|([\w:]+)/gmi) : []`
only English can pass though the regex which chinese words would be filtered.
chinese words regex is [\u4e00-\u9fa5]
so use 
`globalTags = tags ? tags[1].match(/\[\[(.*?)\]\]|#(([\u4e00-\u9fa5]|[\w:\/-])+)|(([\u4e00-\u9fa5]|[\w:])+)/gmi) : []`
maybe fix the bug

The regex problem also maybe occur at the code of macthing "cards-deck" 
regex.ts at line 27
`this.cardsDeckLine = /cards-deck: [\w\d]+/gi`
use following will work
`this.cardsDeckLine = /cards-deck: ([\u4e00-\u9fa5]|[\w\d])+/gi`

I can't "pull request" to fix the bug since our country firewall is so high which cause push/pull to github always failed.
Hope this regex problem be fixed in new version:)

**Comment by reuseman** [comment]
It took me a while to find the time, but now it should be solved 🙂
