### ISSUE TITLE
Allow for NEWLINE and maybe an #endcard tag

### ISSUE THREAD

**Issue by mkschulze** [reuseman/flashcards-obsidian#34]
**Is your feature request related to a problem? Please describe.**
I often would like to add a blank line to separate text for better visibilty. But either it gets interpreted as an error or as end of the flashcard.

**Describe the solution you'd like**
I think it would be great to allow any text styling and make the end of the card clear with an #endcard tag for example.

**Comment by mkschulze** [comment]
Just found I could use <br> tag in between, so that should work as well as an alternative.

**Comment by reuseman** [comment]
@mkschulze you can even use a space. Copy the one below to try it. The solution of #endcard would make things too complicated.

```
Question
#card
Answer1
 
Answer2
```
