### ISSUE TITLE
Question about images 

### ISSUE THREAD

**Issue by fugohan** [reuseman/flashcards-obsidian#49]
The [wiki](https://github.com/reuseman/flashcards-obsidian/wiki#images) says that you can add photos to your Anki cards by declaring the attachment folder. How or where do I do that? 

Would be great if you could add this information in the wiki, because it is not exactly made easy for beginners.

**Comment by reuseman** [comment]
In the previous versions, there was the need to specify the attachment folder path in the settings of Obsidian.

`Settings -> File & Links -> Attachment folder path`

But with the update of yesterday, this is not needed any more. Now it's even easier, just put them wherever you want :)

**Comment by fugohan** [comment]
It works for me if I store the photos in the same folder as the markdown file, but if I create a subfolder for the images Anki does not recognize the images. I hope it will work with the next update. Thanks for your time.
