### ISSUE TITLE
Add examples for code highlighting and latex

### ISSUE THREAD

**Issue by ahtamjidi** [reuseman/flashcards-obsidian#5]
**Is your feature request related to a problem? Please describe.**
It would be nice to add examples that have code highlighting and latex. The code highlighting  
I added this in obsidian 
![image](https://user-images.githubusercontent.com/1119857/102043192-96d01d00-3d88-11eb-9818-f8b47e304282.png)
and got this in anki
![image](https://user-images.githubusercontent.com/1119857/102043387-165dec00-3d89-11eb-936a-bbdbad370165.png)

**Describe the solution you'd like**
I wish I could get the highlighting in anki card as well
![image](https://user-images.githubusercontent.com/1119857/102043483-60df6880-3d89-11eb-8f35-78bcbb2b4676.png)

Thanks for making this great plugin.

**Comment by reuseman** [comment]
Did you enable the code highlight in the settings?

**Comment by ahtamjidi** [comment]
Ah. I missed it. Now the source is highlighted but its text is centered. 
![image](https://user-images.githubusercontent.com/1119857/102167001-503ef900-3e42-11eb-9865-aad65b4b4fa2.png)
I was hoping that the code is left aligned and the code block is center aligned.  I was able to twick

**Comment by pnchinmay** [comment]
@ahtamjidi Could you please share how you tweaked to make it left aligned ?

Edit: Found it. Didn't know Anki allows CSS styling
