### ISSUE TITLE
Multiple errors in the text generated

### ISSUE THREAD

**Issue by dummifiedme** [reuseman/flashcards-obsidian#6]
THere were random insertions of wiki links at random places inside the text of the answer. The wikilinks what were inserted inmidst of the text were from the text itself but were later in the text where they were again present though not highlighted as links. Messed up my cards.

**Comment by reuseman** [comment]
Do you have the last version?

**Comment by dummifiedme** [comment]
Yes. I installed some minutes before posting the issue

**Comment by dummifiedme** [comment]
Nevermind :) 
I wouldn't be able to check on the issue since I have moved to other plugin
