### ISSUE TITLE
What's meaning of space only card?

### ISSUE THREAD

**Issue by YukoOshima** [reuseman/flashcards-obsidian#65]
Sorry for the bother. I wonder what's the difference between `#card` and `#card-spaced`?

**Comment by reuseman** [comment]
The difference is essentialy that:
- #card creates in anki a note where there is a question and an answer.
- #card-spaced it's just a way to show a prompt spaced away in time. For example a quote from a film that once in a while you want to read again. So it's not about knowing the answer, but it's just about seeing it again
