### ISSUE TITLE
The card could not be sent and no id was generated

### ISSUE THREAD

**Issue by vvh-1** [reuseman/flashcards-obsidian#72]
Hello, I like your plugin very much
But I encountered a problem in use
Test shows anki works
But when the card was sent, anki did not receive the card and did not generate the id
The console reports an error `'NoneType' object has no attribute'write'`
At first I thought that anki could not add cards to a deck that did not exist, so I created a deck called Obsidian, but the situation did not change.

**Screenshots**
![image](https://user-images.githubusercontent.com/59473428/147902255-b7e3eb0d-0b15-4a37-8636-35eab72bdc41.png)

**Markdown used**
```md
---
cards-deck: Obsidian
---

## This is the front #card 
This is the back of the card.
```

**Comment by vvh-1** [comment]
I found the same problem after trying other plug-ins. Is it caused by ankiconnet update? Ankiconnet only provides downloads of the latest version. Is it because the functions have changed in the latest version?
Looking forward to your help
Thank you very much

**Comment by reuseman** [comment]
As soon as I can, I will take a look. It could be as you say

**Comment by reuseman** [comment]
@vvh-1 I've just tried but I cannot replicate the bug

**Comment by vvh-1** [comment]
i found the reason
Ankiconnet does not yet support anki 2.1.50 beta version
It works fine with version 2.1.49
