### ISSUE TITLE
Latex star symbol rendered incorrectly?

### ISSUE THREAD

**Issue by GARLICDOG** [reuseman/flashcards-obsidian#73]
**Describe the bug**
When using latex with the * wildcard symbol I get the following render in Obsidian:
![image](https://user-images.githubusercontent.com/23639311/149670006-6654f133-c153-469d-bcdd-9bc5c6b73d5a.png)

This is with the following latex syntax: `$$T=\frac{x_1*x_2}{2}$$`

The same syntax is rendered like this in Anki:
![2022-01-16__18-00__anki_284](https://user-images.githubusercontent.com/23639311/149670037-48d78b3a-7bfc-427c-a417-e3c250f038f6.png)

The multiplier symbol is rendered like this in every equation. If that's any help I previously used Pseudonium's addon, I assume it uses a different way to render Latex syntax but the star symbol worked there correctly.

**To Reproduce**
- Steps to reproduce the behavior:
Use latex syntax with a star symbol like this: `$$T=\frac{x_1*x_2}{2}$$`

**Expected behavior**
Star symbol in equations should render with the normal color (black) and without the backslash.

**Markdown used**
```md
---
cards-deck: Obsidian
---

# test
#card 
$$T=\frac{x_1*x_2}{2}$$
^1642352814157
```

**Additional context**
I have quite a few other addons in case this is working for others I can list those if that provides any clue.

**Comment by reuseman** [comment]
Now it should be fixed
