### ISSUE TITLE
Broken update 1.5.5 

### ISSUE THREAD

**Issue by OctipusPrime** [reuseman/flashcards-obsidian#76]
After the update settings and commands disappear, making it impossible to use the plugin in any way. Fortunately 1.5.4 still works and downgrading is as easy as downloading the files and replacing the 1.5.5 files in the plugin folder.

**Comment by reuseman** [comment]
@OctipusPrime I cannot replicate your problem. I can see the settings and the command

**Comment by reuseman** [comment]
@OctipusPrime Sorry, you were right. There was a problem with the build that I did not have on my machine. Now it works

**Comment by psychsatani** [comment]
I have 1.6.2 build but I dont see the command anymore. Should I downgrade?
