### ISSUE TITLE
Broken Latex Syntax Support 

### ISSUE THREAD

**Issue by fugohan** [reuseman/flashcards-obsidian#80]
**NOTE: Do you have the last version of the plugin? If not that's probably the problem**
yes 
**Describe the bug**
The plugin detects latex code as cloze card.

**Markdown used**
```md
$$\begin{equation}1234
^1644149848071
\iiiint
\end{equation}$$
```

I would suggest to remove the cloze support for {...} and just use ==...== or {1:...}

**Comment by fugohan** [comment]
I dont know how to regex but maybe this query would work? 

```regex
/({)+\d+.+(})/g
```

I tested it and I think it would work but I dont know where to change the regex query. But here is a screenshot about the result of the query. 
![Selection_186](https://user-images.githubusercontent.com/46691165/152699814-747b52c0-3c2d-4f86-93cf-cf9b4fc78422.png)

**Comment by reuseman** [comment]
That's a good solution, but I think that we can do better. I will identify math blocks and if some cloze is inside, then it will not be considered.

**Comment by reuseman** [comment]
Now it should work
