### ISSUE TITLE
Various Issues with Cloze-Format

### ISSUE THREAD

**Issue by Weyaaron** [reuseman/flashcards-obsidian#81]
**NOTE: Do you have the last version of the plugin? If not that's probably the problem**

I just made sure I use the last version, since there have been recent changes. I am on 1.6.1.

**Describe the bug**
Various pieces of the cloze-support are broken:
- Not all cards are rendered
- Some of the cards are broken

**To Reproduce**
- Steps to reproduce the behavior:
1: Setup a card with the content 
```
---
cards-deck: Test
---
{1: A} {2: B} {3: C} {4: D} #card
```
2. Check Anki for the results 

**Expected behavior**
That the plugin adds 4 cards with functioning clozes. 

**Screenshots**
First Card generated:
![image](https://user-images.githubusercontent.com/52529582/152967773-03c61aad-bb0b-4be1-84cc-10b706d5fcde.png)

Second Card generated:
![image](https://user-images.githubusercontent.com/52529582/152967803-862378be-c1d4-42bd-9e0e-b6ec13989748.png)

View on the side of Obsidian:
![image](https://user-images.githubusercontent.com/52529582/152967905-86e38485-60a0-4ea0-85c0-85bf2380450f.png)

**Additional context**
This broke a on a lot of cards and I tried some debugging on my own, including:
- Deleting the generated cards 
- Altering the whitespace
- Altering the Layout of cards from single to multiline and vice versa

I will gladly help with further questions :)

**Comment by reuseman** [comment]
Hey @Weyaaron. Why are you using the #card tag if you want a cloze one?

**Comment by Weyaaron** [comment]
Ah, I see. This is the obvious solution, never mind the issues. 
Maybe there is room for improvement on the documentation such that the documentation warns about this mistake?

**Comment by reuseman** [comment]
Honestly, I would really love to maintain it as simple as possible. Right now, the goal is that people can just copy a simple snippet and paste it to have what they want to achieve. But if we add all the possible gotchas, then it will be extremely huge. What would you change in the documentation specifically?

**Comment by Weyaaron** [comment]
Thats a good point. Since this issue is public, a person that will open a new issue will probably stumble over this issue first anyway, so this issue serves as a documentation as well. 
I retract my point, thanks for the quick help, I appreciate it!
