### ISSUE TITLE
How to connect Obsidian to Anki? Where is "Paste the configuration below"

### ISSUE THREAD

**Issue by chumido98** [reuseman/flashcards-obsidian#87]
Hi. I can't connect obsidian to Anki.

I installed plugin
i installed AnkiConnect plugin
But i don't know how to config plugin. Can someone help me? Thank you very much

**Comment by reuseman** [comment]
Oh I did not remove the line about the pasting configuration. There is a new method that is 

> Open the settings of the plugin, and while Anki is opened press "Grant Permission"

**Comment by chumido98** [comment]
> 

I did. But obsidian report "Something is wrong, is Anki open?" What did i miss?

**Comment by chumido98** [comment]
Ok, it worked. Thank you very much.

**Comment by macrospecter** [comment]
I'm getting the same error on Obsidian's side. I have AnkiConnect installed.
