### ISSUE TITLE
Cloze support

### ISSUE THREAD

**Issue by glitchlover** [reuseman/flashcards-obsidian#9]
**Describe the solution you'd like**

Cloze support in sentence like "Her age is {{10}} years old". Then convert it to anki like "Her age is {{c1::10}} years old" would be perfect for plugin feature

**Comment by reuseman** [comment]
Yeah, it's actually in the [roadmap](https://github.com/reuseman/flashcards-obsidian/projects), but these days I am quite busy. So pull request are really welcomed.

**Comment by glitchlover** [comment]
No worries you have done great job silently.
this one is best from the other two add-ons from my perspective.

**Comment by mkschulze** [comment]
This would be really nice yes. Any news on your schedule maybe? :)

**Comment by reuseman** [comment]
@mkschulze I am even more busy than the other time but if someone wants to implement the cloze support, it should not be incredibly difficult.

**Comment by ianscottknight** [comment]
+1

**Comment by reuseman** [comment]
Now it is implemented.

You can use it in several ways
==This is a cloze== but even {this one is a cloze} or if you want to have an order, than {2:this is a cloze too}
