### ISSUE TITLE
Wikilinks problem

### ISSUE THREAD

**Issue by maley-typek** [reuseman/flashcards-obsidian#92]
**Describe the bug**
The bug is that the wikilinks is showned like in source mode [[#example]]

**Expected behavior**
Is there a way to disable hyperlink in Anki and make [[#example]] -> example ?

**Screenshots**
![image](https://user-images.githubusercontent.com/88964826/156381197-751c6440-8236-4d74-8dab-3a5ddd38b030.png)

**Markdown used**
#### Pojistná smlouva📝
#card 
- Smlouva o službě pojištění
	- Pojišťovna ([[#pojistitel🏢]]) se zavazuje poskytnou [[#pojistné plnění🤑]] pojištěnému v případě [[#Pojistná událost🔥|pojistné události🔥]]
	- [[#Pojistník👨]] se zavazuje platit [[#pojistné💸]]
^1646229583968

**Additional context**
I am sorry for my bad english and I am new on github

**Comment by maley-typek** [comment]
> So you want to disable the hyperlink and hence do not have anymore `[[Example]]` and have just `Example`. But `Example` should be clickable or not?

It should not be clickable

**Comment by Jonass-K** [comment]
I think it should be clickable. Only enhancement I would make, is to remove the brackets. I made it already for myself and can pr the mini changes
